# Generated by Django 5.0.5 on 2024-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_main',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
