# Generated by Django 5.0.5 on 2024-06-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon_main_especies',
            unique_together={('species', 'name')},
        ),
    ]
