# Generated by Django 5.0.5 on 2024-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0002_alter_pokemon_main_especies_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon_main_evolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolutions', models.CharField(max_length=255)),
            ],
        ),
    ]
