# Generated by Django 5.0.5 on 2024-06-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0002_pokemon_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon_main',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemon_main',
            name='unique_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
