# Generated by Django 5.0.5 on 2024-06-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0003_remove_pokemon_main_id_alter_pokemon_main_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_main',
            name='possible_values',
            field=models.CharField(max_length=255),
        ),
    ]
